services:
  - type: web
    name: mrca-students-hub-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
    envVars:
      - key: VITE_API_URL
        value: https://new-4rqi.onrender.com/api